# Generated by Django 4.1.5 on 2023-01-20 19:40

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('role', models.CharField(choices=[('crm-admin', 'CRM-Admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=9, verbose_name='Роль')),
                ('offer', models.BooleanField(default=False, verbose_name='Коммерческое предложение')),
                ('avatar', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Dev/test_tasks/compas-pro/compaspro_test_task/test_task/media/avatars'), verbose_name='Аватар')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
